# Generated by Django 3.0.5 on 2020-04-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200404_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
    ]
