# Generated by Django 3.0.5 on 2020-04-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200406_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='slug field', max_length=255),
            preserve_default=False,
        ),
    ]
